Traceback (most recent call last):
  File "main_from_args.py", line 5, in <module>
    from openea.modules.args.args_hander import check_args, load_args
  File "/home/galmagro/OpenEA/src/openea/__init__.py", line 19, in <module>
    from openea import models
  File "/home/galmagro/OpenEA/src/openea/models/__init__.py", line 1, in <module>
    from openea.models import trans
  File "/home/galmagro/OpenEA/src/openea/models/trans/__init__.py", line 1, in <module>
    from openea.models.trans.transe import TransE
  File "/home/galmagro/OpenEA/src/openea/models/trans/transe.py", line 1, in <module>
    import tensorflow as tf
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 47, in <module>
    import numpy as np
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/numpy/__init__.py", line 151, in <module>
    from . import random
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/numpy/random/__init__.py", line 179, in <module>
    from . import _pickle
  File "/home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/numpy/random/_pickle.py", line 3, in <module>
    from ._pcg64 import PCG64
ImportError: /home/galmagro/anaconda3/envs/openea/lib/python3.6/site-packages/numpy/random/_pcg64.cpython-36m-x86_64-linux-gnu.so: invalid ELF header
